# Generated by Django 5.2.7 on 2025-11-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilaluno',
            name='curso_desejado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfilaluno',
            name='dias_disponiveis',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='perfilaluno',
            name='horario_preferido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfilaluno',
            name='nivel_ingles',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfilaluno',
            name='objetivo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
