# Generated by Django 5.2.7 on 2025-11-03 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetoapp', '0004_perfilaluno_bairro_perfilaluno_cep_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('preco_mensal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('PENDENTE', 'Pendente'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=10)),
                ('data_matricula', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='projetoapp.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField(help_text='Use o dia 1 do mês de referência, ex: 2025-11-01')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PAGO', 'Pago'), ('PENDENTE', 'Pendente'), ('ESTORNADO', 'Estornado')], default='PENDENTE', max_length=10)),
                ('pago_em', models.DateTimeField(blank=True, null=True)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='projetoapp.matricula')),
            ],
        ),
        migrations.AddConstraint(
            model_name='matricula',
            constraint=models.UniqueConstraint(fields=('aluno', 'curso'), name='unique_matricula_por_curso'),
        ),
        migrations.AddIndex(
            model_name='pagamento',
            index=models.Index(fields=['competencia'], name='projetoapp__compete_68b828_idx'),
        ),
        migrations.AddIndex(
            model_name='pagamento',
            index=models.Index(fields=['status'], name='projetoapp__status_39115a_idx'),
        ),
        migrations.AddIndex(
            model_name='pagamento',
            index=models.Index(fields=['pago_em'], name='projetoapp__pago_em_f0a8ea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pagamento',
            unique_together={('matricula', 'competencia')},
        ),
    ]
