# Generated by Django 5.2.7 on 2025-11-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetoapp', '0005_curso_matricula_pagamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='capa_curso',
            field=models.ImageField(blank=True, null=True, upload_to='cursos/capas/', verbose_name='Capa do Curso'),
        ),
        migrations.AddField(
            model_name='curso',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='modalidade',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('online', 'Online')], default='presencial', max_length=20),
        ),
        migrations.AddField(
            model_name='curso',
            name='tipo',
            field=models.CharField(choices=[('turma', 'Turma'), ('executivo', 'Executivo'), ('vip', 'VIP')], default='turma', max_length=20),
        ),
        migrations.DeleteModel(
            name='Pagamento',
        ),
    ]
