# Generated by Django 5.2.7 on 2025-11-04 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetoapp', '0006_curso_capa_curso_curso_descricao_curso_modalidade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='preco_mensal',
            new_name='preco_mes',
        ),
    ]
