# Generated by Django 5.2.7 on 2025-11-05 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetoapp', '0007_rename_preco_mensal_curso_preco_mes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Turma')),
                ('horario', models.CharField(blank=True, help_text='Ex: 19:00 - 20:30', max_length=100, null=True)),
                ('dias', models.CharField(blank=True, help_text='Ex: Segundas e Quartas', max_length=100, null=True)),
                ('alunos', models.ManyToManyField(blank=True, related_name='turmas_onde_esta_matriculado', to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turmas_do_curso', to='projetoapp.curso')),
                ('responsavel', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='materiais/%Y/%m/')),
                ('link', models.URLField(blank=True, null=True)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='projetoapp.turma')),
            ],
        ),
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('mensagem', models.TextField()),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicados', to='projetoapp.turma')),
            ],
            options={
                'ordering': ['-data_publicacao'],
            },
        ),
    ]
