# Generated by Django 5.2.7 on 2025-11-05 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetoapp', '0008_turma_material_comunicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='turma',
            name='max_alunos',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='turma',
            name='status',
            field=models.CharField(choices=[('ABERTA', 'Inscrições Abertas'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDA', 'Concluída')], default='ABERTA', max_length=20),
        ),
    ]
